name: Build Plugin

on:
    push:
        branches: "mc_1201-java17-3.3.1"
    pull_request:
        branches: "mc_1201-java17-3.3.1"
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "adopt"

            - name: Build with Gradle
              run: |
                  chmod +x gradlew
                  ./gradlew build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Plugin
                  path: build/libs/*.jar

            - name: Upload to release
              if: github.event_name == 'release'
              uses: softprops/action-gh-release@v2
              with:
                  files: build/libs/*.jar
